version: '3.4'

services:
  softplan.calculajuros.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
    networks:
      - taxajurosnet
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  softplan.taxajuros.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6001:80"
    networks:
      - taxajurosnet
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
